### PR TITLE
feat: Add block header to state test vectors

### PR DESCRIPTION
**Pull request by morph-dev**
Clients should verify state network content using state root, and usually the only way to get to the valid state root is via block header.

Therefore, in order to do end-to-end tests properly, we need to provide block headers as well.

**Note:** The block headers that I included are just the `rlp(header)`, not the corresponding content value from the history network. Let me know if you believe that those should be included instead.

### CODE REVIEW

**Comment by kdeme** [comment]
cc @web3-developer

**Review by KolbyML — APPROVED** [review]
:shipit:

**Comment by web3-developer** [comment]
Why do we need to add the block header here? The offer values already contain the blockHash which identifies the block to validate against and the stateRoot is the only value needed by the state network from the block header. In my tests I am doing something like this: 
`mockBlockHashToStateRoot(contentValue.blockHash, stateRoot)`

so that when the code looks up the block by block hash the correct state root is used in the state validation.

**Comment by morph-dev** [comment]
> so that when the code looks up the block by block hash the correct state root is used in the state validation.

@web3-developer Yes, that can be used in unit tests, but not really in integration / end-to-end tests, like hive. I would say those tests need full headers, and depending on the implementation maybe even more (i.e. entire content-value from the history network - header with proof).

**Comment by web3-developer** [comment]
> > so that when the code looks up the block by block hash the correct state root is used in the state validation.
> 
> @web3-developer Yes, that can be used in unit tests, but not really in integration / end-to-end tests, like hive. I would say those tests need full headers, and depending on the implementation maybe even more (i.e. entire content-value from the history network - header with proof).

I see. I guess in these tests you might want to seed the history network with the block headers so that the state network can lookup the header and pull out the state root.

**Comment by morph-dev** [comment]
> I see. I guess in these tests you might want to seed the history network with the block headers so that the state network can lookup the header and pull out the state root.

Yes, that's the plan.

---

I will merge this as is, as I believe we don't lose anything by having more data than before when we clearly need this data in some situations (e.g. hive tests).

**Pull request merged**
