### PR TITLE
feat: add 2 epoch accumulator content key/value to hive tests

### PR DESCRIPTION
**Pull request by KolbyML**
@kdeme @njgheorghita @acolytec3 @njgheorghita for review

Adds 2 epoch accumulators to history hive test file

### CODE REVIEW

**Comment by acolytec3** [comment]
Also, seems like epoch accumulators are misplaced in this file given the name (fork blocks...) but otherwise looks good for a start!

**Comment by KolbyML** [comment]
> These epoch accumulators are already big on their own (especially when drop in hex vs ssz). Adding them in this already big yaml file becomes maybe a bit much?

the file is only 3.2mb which is very small no?

**Comment by KolbyML** [comment]
> Also, seems like epoch accumulators are misplaced in this file given the name (fork blocks...) but otherwise looks good for a start!

we can change the name to hive_history_content or something

**Comment by KolbyML** [comment]
@kdeme would I be able to merge this so we have coverage for this on hive? Since this is only used for hive I think it being 3.2mb is fine for now

**Comment by ogenev** [comment]
@KolbyML Could you elaborate on how this data will be used in hive? Please briefly describe the test you want to run and how this relates to epoch accumulators.

**Comment by KolbyML** [comment]
> But I'm still in favour of having the test vectors more separated in such way that each vector represents a test case. It is more easy to go through and edit the test vectors that way, they are smaller and they can be encoded differently per vector.

This format is required for Trin-bridge tests, also because of how history is structured having tests be auto generated from this file is easy

**Pull request merged**
